# Generated by Django 5.0.6 on 2024-06-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_product_regular_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='updated_at',
        ),
    ]
