# Generated by Django 5.0.6 on 2024-06-18 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MaxLengthValidator(20, message='phone number must no exceed 20 characters')]),
        ),
    ]
