# Generated by Django 5.0.6 on 2024-06-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customeruser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_thumbnail',
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
