# Generated by Django 5.0.6 on 2024-06-18 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MaxLengthValidator(20, message='phone number must no exceed 20 characters'), django.core.validators.RegexValidator(message='phone number must only contain digits', regex='^\\d+$')]),
        ),
    ]
