# Generated by Django 5.0.6 on 2024-06-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_customeruser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='alternative_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
