# Generated by Django 5.0.6 on 2024-06-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_shippingaddress_customeruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='e3233c57-d638-4d72-af86-183fdfa0a064', max_length=255, null=True, unique=True),
        ),
    ]
