# Generated by Django 5.0.6 on 2024-06-28 02:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(20, message='phone number must no exceed 20 characters'), django.core.validators.RegexValidator(message='phone number must only contain digits', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='48022a0b-80de-45cb-952d-607172e7ce96', max_length=255, null=True, unique=True),
        ),
    ]
