# Generated by Django 5.0.6 on 2024-06-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='6a59eaed-5e0d-42b6-910f-cd543a6a5dc6', max_length=255, null=True, unique=True),
        ),
    ]
