# Generated by Django 5.0.6 on 2024-06-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='85df4c87-641b-461a-8774-b5383bb7c353', max_length=255, null=True, unique=True),
        ),
    ]
