# Generated by Django 5.0.6 on 2024-06-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='592bc2f6-58b0-42ac-8312-5542f1afc29f', max_length=255, null=True, unique=True),
        ),
    ]
