# Generated by Django 5.0.6 on 2024-06-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='e9d4f4bb-2318-4f95-b8d3-f59936985e72', max_length=255, null=True, unique=True),
        ),
    ]
