# Generated by Django 5.0.6 on 2024-07-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('W', 'Wating To Be Confirmed'), ('S', 'Shipped'), ('D', 'Delivered'), ('R', 'Returned'), ('X', 'Cancelled')], default='P', max_length=255),
        ),
    ]
