# Generated by Django 5.0.6 on 2024-07-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_customeruser_is_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='is_guest',
        ),
    ]
