# Generated by Django 5.0.6 on 2024-07-07 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(20, message='phone number must no exceed 20 characters'), django.core.validators.RegexValidator(message='phone number must only contain digits', regex='^\\d+$')]),
        ),
    ]
