# Generated by Django 5.0.6 on 2024-07-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='verification_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='verification_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
